### PR TITLE
Add go module & set import path to capnproto.org/go/capnp/v3

### LINKED ISSUE #166: Change import path to capnproto.org/go/capnp
Pinging @zombiezen @kentonv .

As part of https://github.com/capnproto/go-capnproto2/pull/165, it has become necessary to instantiate a go module around this project.  @taylorjdawson Initially tried to do the obvious, sensible thing and instantiate it with `go mod init github.com/capnproto/go-capnproto2`, with [predictable results](https://github.com/capnproto/go-capnproto2/pull/165#issuecomment-789926742) (at the risk of explaining the joke,  he should have used `zombiezen.com/go/capnproto2`).  This detail has briefly confused me on occasion as well, and I worry that it might frustrate new Go developers.

Additionally, many editors are configured to add a package alias when the last segment does not match the package name.  Ross [recently brought this up during code review](https://github.com/capnproto/go-capnproto2/pull/161#discussion_r575696053) and I ended up merging it anyway, after trying to figure out how to edit my VSCode configuration for 20 minutes without success. 😞 

After discussing this in slack with @zenhack and @taylorjdawson, we're of a mind to to change all the import paths in the project from `zombiezen.com/go/capnproto2` to (ideally) `capnproto.org/go/capnp`.

@zombiezen Is that okay with you?  In addition to asking if this might have technical consequences, I wanted to check that you were okay with this first because it's always a bit delicate when the new guys start rebranding something you built!

@kentonv Assuming ross is onboard with this, would you be willing to add the appropriate `<meta>` tag so that we could import this project as `capnproto.org/go/capnp`?

Miscellaneous thought:  I think this is probably safe to do since we're working towards a major version bump anyway.

### PR DESCRIPTION
**Pull request by lthibault**
Fixes #166.

- Add `go.mod` with import path as `capnproto.org/go/capnp/v3`
- Update import paths in all files

### CODE REVIEW

**Comment by lthibault** [comment]
```
$ go test ./...
--- FAIL: TestMarshalPackedShouldMatchTextWhenDecoded (0.14s)
    integration_test.go:762: zdataFilledMessage(20): decoded to:
        "(zdata = (data = \"\\000\\001\\002\\003\\004\\005\\006\\a\\b\\t\\n\\v\\f\\r\\016\\017\\020\\021\\022\\023\"))\n"; want:
        "(zdata = (data = \"\\x00\\x01\\x02\\x03\\x04\\x05\\x06\\a\\b\\t\\n\\v\\f\\r\\x0e\\x0f\\x10\\x11\\x12\\x13\"))\n"
--- FAIL: TestMarshalShouldMatchTextWhenDecoded (0.15s)
    integration_test.go:739: zdataFilledMessage(20): decoded to:
        "(zdata = (data = \"\\000\\001\\002\\003\\004\\005\\006\\a\\b\\t\\n\\v\\f\\r\\016\\017\\020\\021\\022\\023\"))\n"; want:
        "(zdata = (data = \"\\x00\\x01\\x02\\x03\\x04\\x05\\x06\\a\\b\\t\\n\\v\\f\\r\\x0e\\x0f\\x10\\x11\\x12\\x13\"))\n"
FAIL
FAIL    capnproto.org/go/capnp/v3       0.336s
--- FAIL: TestRemoteScope (0.00s)
    capnpc-go_test.go:217: different file struct: g.RemoteTypeName(nodes[0x836faf1834d91729].Const().Type(), nodes[0x836faf1834d91729]); g.imports = otherscopes "zombiezen.com/go/capnproto2/capnpc-go/testdata/otherscopes"; want otherscopes "capnproto.org/go/capnp/v3/capnpc-go/testdata/otherscopes"
    capnpc-go_test.go:217: different file struct list: g.RemoteTypeName(nodes[0x83e7e1b3cd1be338].Const().Type(), nodes[0x83e7e1b3cd1be338]); g.imports = otherscopes "zombiezen.com/go/capnproto2/capnpc-go/testdata/otherscopes"; want otherscopes "capnproto.org/go/capnp/v3/capnpc-go/testdata/otherscopes"
    capnpc-go_test.go:236: different file struct: g.RemoteTypeNew(nodes[0x836faf1834d91729].Const().Type(), nodes[0x836faf1834d91729]); g.imports = otherscopes "zombiezen.com/go/capnproto2/capnpc-go/testdata/otherscopes"; want otherscopes "capnproto.org/go/capnp/v3/capnpc-go/testdata/otherscopes"
    capnpc-go_test.go:236: different file struct list: g.RemoteTypeNew(nodes[0x83e7e1b3cd1be338].Const().Type(), nodes[0x83e7e1b3cd1be338]); g.imports = otherscopes "zombiezen.com/go/capnproto2/capnpc-go/testdata/otherscopes"; want otherscopes "capnproto.org/go/capnp/v3/capnpc-go/testdata/otherscopes"
FAIL
FAIL    capnproto.org/go/capnp/v3/capnpc-go     0.636s
FAIL
```

@zenhack Is this a known issue?  (_i.e._ should I worry about it?)

**Comment by zenhack** [comment]
@lthibault, I think you forgot to re-generate some test data:

```
[isd@elf go-capnproto2]$ git grep zombiezen\.com/go
Binary file capnpc-go/testdata/aircraft.capnp.out matches
Binary file capnpc-go/testdata/const.capnp.out matches
Binary file capnpc-go/testdata/group.capnp.out matches
Binary file capnpc-go/testdata/rpc.capnp.out matches
Binary file capnpc-go/testdata/scopes.capnp.out matches
Binary file capnpc-go/testdata/util.capnp.out matches
```

**Comment by lthibault** [comment]
> @lthibault, I think you forgot to re-generate some test data:

@zenhack  Right on.  What's the process for regenerating test data?  I can't seem to find anything 🤔

**Comment by zenhack** [comment]
I'm not sure what the official way to regenerate those is; @zombiezen?

I assume they're just the output of `capnp compile -o- /path/to/schema.capnp > schema.capnp.out`, with appropriate flags.

**Comment by lthibault** [comment]
Alright, I've manually regenerated the test data for `capnpc-go/testdata`, and that seems to work well.

Concerning the errors in `integration_test.go`, the test data appears to be valid.

```go
{
    name: "zdataFilledMessage(20)",
    msg:  zdataFilledMessage(t, 20),
    typ:  "Z",
    text: `(zdata = (data = "\x00\x01\x02\x03\x04\x05\x06\a\b\t\n\v\f\r\x0e\x0f\x10\x11\x12\x13"))` + "\n",
    data: []byte{
        0, 0, 0, 0, 9, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 1, 0,
        28, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 162, 0, 0, 0,
	0, 1, 2, 3, 4, 5, 6, 7,
	8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 0, 0, 0, 0,
    },
},
```

Updating the `text` field appears to solve the issue.

Old:  `\x00\x01\x02\x03\x04\x05\x06\a\b\t\n\v\f\r\x0e\x0f\x10\x11\x12\x13`
New: `\000\001\002\003\004\005\006\a\b\t\n\v\f\r\016\017\020\021\022\023`

I'm not sure I understand the root cause.  Has Go's representation of binary data recently changed or something?

**Comment by zenhack** [comment]
The text field is what the test expects `capnp decode` to output, so my guess is that at some point since this test was written, that command starting using octal escaping instead of hex  when formatting (@kentonv?)

Anyway, LGTM.

**Review by zenhack — APPROVED** [review]

**Comment by lthibault** [comment]
@zenhack Yeah, that was my instinct as well and I've managed to reproduce the output at the command line:

```
$ cat /tmp/zdataFilled20.out | capnp convert binary:text internal/aircraftlib/aircraft.capnp Z
( zdata = (
    data = "\000\001\002\003\004\005\006\a\b\t\n\v\f\r\016\017\020\021\022\023" ) )
```

Merging now.

**Comment by kentonv** [comment]
Looks like the switch from hex to octal happened here: https://github.com/capnproto/capnproto/commit/03800dfa0b8ce21e549715e1b42dd0eebf63b485

Looks like it was not entirely advertent. But, hex escapes do have the drawback that in many languages (including C/C++), they are technically not limited to two digits, and so a string like `"\x012"` is technically equivalent to `"\x12"`. This makes it really hard to output an arbitrary string with hex escapes correctly, since any valid hex digit appearing immediately after an escape has to be escaped, too. Octal escapes, on the other hand, are never more than three digits, so that's much easier to deal with.

**Pull request merged**
