### PR TITLE
Move calls to ans.releaseMsg() inside ans.destroy()

### PR DESCRIPTION
**Pull request by zenhack**
These always go together, so let's remove some boilerplate.

---

Note, this is stacked on top of #370, because it touches nearby code and I didn't want to deal with conflicts. That should be merged first.

### CODE REVIEW

**Comment by zenhack** [comment]
Failure looks like the data race we were getting before #349. Re-running.

**Comment by lthibault** [comment]
Can you rebase onto `main` now that #370 is merged?  For some reason, my eyes are having trouble parsing.

**Comment by zenhack** [comment]
Done

**Review by lthibault — APPROVED** [review]
Now I see it!  Looks good 👍

**Pull request merged**
