### PR TITLE
Clean up/fix locking in handleDisembargo

### PR DESCRIPTION
**Pull request by zenhack**
- Avoid syncutil.Without
- Hold c.lk when invoking sendMessage().

The latter requires us to move some of the release()es later, but this is fine.

### CODE REVIEW

**Review by lthibault — APPROVED** [review]

**Comment by zenhack** [comment]
Failure looks like #348; re-running.

**Comment by zenhack** [comment]
#377, let's try again

**Comment by zenhack** [comment]
#394

**Comment by zenhack** [comment]
#377 again. @lthibault do you have a strong objection to just merging this?

**Comment by lthibault** [comment]
SGTM.  Send it :)

**Pull request merged**
