### PR TITLE
Fix client leak in the server package

### PR DESCRIPTION
**Pull request by zenhack**
@lthibault found this in production; the test is distills the failure case.

The culprit seems to be a missing call to Promise.ReleaseClients() in the server package; this now mirrors the ReleaseFuncs returned by other implementations of ClientHook.

### CODE REVIEW

**Comment by zenhack** [comment]
@lthibault, FYI we have a custom test main that calls SetClientLeakFunc, so there's no need to set it manually in an individual test; it should detect leaks in any test automatically. (Just pushed another commit that fixes a data race that was caused by this).

**Comment by zenhack** [comment]
That's a new one:

https://github.com/capnproto/go-capnproto2/actions/runs/3707839611/jobs/6284731111#step:5:1569

**Review by lthibault — DISMISSED** [review]
LGTM.  Thanks for handling this one.

Not sure how you want to handle the test failure, so I'll leave the decision to merge up to you.

**Comment by zenhack** [comment]
Pushed a fix for the "new" bug

**Review by lthibault — APPROVED** [review]

**Pull request merged**
