### PR TITLE
sendCap: emit receiverAnswer when appropriate.

### PR DESCRIPTION
**Pull request by zenhack**
I need to do some testing before we should merge this, but this patch should have us emitting `receiverAnswer` where appropriate. Marking as a draft now, but this is representative.

### CODE REVIEW

**Comment by zenhack** [comment]
Added versions of the tests from before but that actually use the client interface, and the pass. I'm also experimenting with this in the application that motivated me to build all this out, and it works... intermittently. So there's still some debugging to do before this can be merged.

**Comment by zenhack** [comment]
N.B. I've merged #215 into this; that pr should be reviewed & merged first

**Comment by zenhack** [comment]
@lthibault, this is probably worth of review; see #216 wrt. the latest in the debugging saga.

**Review by lthibault — APPROVED** [review]

**Comment by zenhack** [comment]
I've merged #219 into this, so it should be good to go, though that should be reviewed & merged on its own first.

**Review by lthibault — APPROVED** [review]

**Comment by lthibault** [comment]
LGTM.  This is marked WIP, so holding off on the merge, just to be safe.

**Comment by zenhack** [comment]
Ah, yeah, forgot to change that. I'll hit merge then.

**Pull request merged**
