### PR TITLE
Remove redundant call to setAnswerQuestion

### PR DESCRIPTION
**Pull request by zenhack**
There's already a call to this in newQuestion, so this is unnecessary.

---

@lthibault, I seem to recall you having submitted a PR that removed this line, and that change got backed out. Staring at it with nothing else going on, it's clear that this change makes sense, I guess I didn't process it at the time since the change seemed unrelated.

### CODE REVIEW

**Comment by zenhack** [comment]
Hm, test failures. Going to mark as a draft until I can investigate further.

**Comment by lthibault** [comment]
I wonder if these tests might not be fixed by #261.

**Comment by zenhack** [comment]
We can check once it's merged.

**Comment by lthibault** [comment]
Just tested against `main` and it seems like #261 did the trick! 🎉 
Feel free to rebase & merge when you're ready.  I don't think it requires another review.

**Comment by zenhack** [comment]
Alright, I merged main back in and if CI passes I'll hit the button.

**Pull request merged**
